wizard_spells = {
    "Pillar of Fire": ["Nagafen", "Proximity"],
    "Project Lightning": ["Fulguration", "Periphery"],
    "Fire Spiral of Al'Kabor": ["Al'Kabor", "Velious"],
    "Cast Force": ["Disassociation", "Presence"],
    "Column of Lightning": ["Trauma", "Xegony"],
    "Lightning Storm": ["Karana", "Xegony"],
    "Energy Storm": ["Fulguration", "Karana"],
    "Shock Spiral of Al'Kabor": ["Al'Kabor", "Helix", "Rallos Zek"],
    "Circle of Force": ["Banding", "Catalyst", "Concussion"],
    "Lava Storm": ["Concussion", "Cyclone", "Solusek Ro"],
    "Thunderclap": ["Conception", "Contortion", "Howling"],
    "Gravity Flux": ["Attraction", "Inverse", "Rathe"],
    "Ice Comet": ["Astral", "Frost"],
    "Paralyzing Earth": ["Crippling", "Rathe"],
    "Supernova": ["Astral", "Impetus"],
    "Wrath of Ap'Sagor": ["Ap'Sagor", "Concussion"],
}