"""
This is intended more for use as the list of spells to sell from the bank.

Missing from this list are all the research spells.

This isn't a comprehensive list of all class spells.
"""

classes = {

    'cleric': [
        "Improved Invis to Undead",
        'Word of Souls',
        "Death Pact",
        "Sunskin",
        "Heroic Bond",
        "Upheaval",
        "Word of Vigor",
        "Yaulp IV",
        "Reckoning",
        "Unswerving Hammer",
        "Fortitude",
        "Stun Command",
        "Wake of Tranquility",
        "Mark of Karn",
        "Aegis",
        "Word of Restoration",
        "Enforced Reverence",
        "Naltron's Mark",
        "The Unspoken Word",
        "Aegolism",
        "Banishment of Shadows",
        "Divine Intervention",
        "Word of Redemption",
        "Exile Undead",
        "Improved Invis vs Undead",
    ],
    'druid': [
        "Repulse Animal",
        "Legacy of Spike",
        "Improved Superior Camouflage",
        "Circle of Winter",
        "Upheaval",
        "Call of Karana",
        "Circle of Summer",
        "Egress",
        "Glamour of Tunare",
        "Spirit of Scale",
        "Blizzard",
        "Form of the Howler",
        "Girdle of Karana",
        "Nature Walkers Behest",
        "Tunare's Request",
        "Tunare`s Request",
        "Breath of Karana",
        "Wake of Karana",
        "Bonds of Tunare",
        "Frost",
        "Succor",
        "Fist of Karana",
        "Regrowth of the Grove",
        "Legacy of Thorn",
        "Spirit of Oak",
        "Banishment",
        "Entrapping Roots",
        "Form of the Hunter",
        "Mask of the Hunter",
        "Protection of the Glades",
        "Circle of Great Divide",
        "Circle of Wakening Lands",
        "Circle of Cobalt Scar",
        "Fixation of Ro",
    ],
    'enchanter': [
        "Ultravision",
        "Wandering Mind",
        "Boon of the Garou",
        "Improved Invisibility",
        "Theft of Thought",
        "Wake of Tranquility",
        "Boon of the Clear Mind",
        "Color Slant",
        "Cripple",
        "Recant Magic",
        "Clarity II",
        "Dementia",
        "Gift of Insight",
        "Largarn`s Lamentation",
        "Wind of Tishani",
        "Zumaik's Animation",
        "Zumaik`s Animation",
        "Augment",
        "Torment of Argli",
        "Enlightenment",
        "Forlorn Deeds",
        "Umbra",
        "Bedlam",
        "Asphyxiate",
        "Gift of Pure Thought",
        "Dictate",
        "Gift of Brilliance",
        "Visions of Grandeur",
        "Wind of Tishanian",
    ],
    'magician': [
        "Summon Shard of the Core",
        "Elemental Maelstrom",
        "Monster Summoning II",
        "Gift of Xev",
        "Scintillation",
        "Bristlebane's Bundle",
        "Bristlebane`s Bundle",
        "Vocarate: Fire",
        "Boon of Immolation",
        "Quiver of Marr",
        "Vocarate: Air",
        "Bandoleer of Luclin",
        "Scars of Sigil",
        "Vocarate: Water",
        "Burnout IV",
        "Call of the Hero",
        "Pouch of Quellious",
        "Rage of Zomm",
        "Wrath of the Elements",
        "Dyzil's Deafening Decoy",
        "Dyzil`s Deafening Decoy",
        "Summon: Muzzle of Mardu",
        "Eye of Tallon",
        "Greater Vocaration: Fire",
        "Velocity",
        "Greater Vocaration: Air",
        "Manastorm",
        "Aegis of Ro",
        "Banishment",
        "Greater Vocaration: Water",
        "Mala",
        "Monster Summoning III",
        "Burnout IV",
    ],
    'necromancer': [
        'Harmshield',
        'Word of Souls',
        "Malignant Dead",
        "Chilling Embrace",
        "Corporeal Empathy",
        "Incinerate Bones",
        "Dead Men Floating",
        "Improved Invis to Undead",
        "Sacrifice",
        "Splurt",
        "Defoliation",
        "Scent of Terris",
        "Convergence",
        "Minion of Shadows",
        "Shadowbond",
        "Thrall of Bones",
        "Augmentation of Death",
        "Chill Bones",
        "Conglaciation of Bone",
        "Infusion",
        "Levant",
        "Sedulous Subversion",
        "Servant of Bones",
        "Conjure Corpse",
        "Quivering Veil of Xarn",
        "Devouring Darkness",
        "Emissary of Thule",
        "Arch Lich",
        "Banishment of Shadows",
        "Demi Lich",
        "Enslave Death",
        "Gangrenous Touch of Zum'uul",
        "Gangrenous Touch of Zum`uul",
        "Trucidation",
        "Summon Corpse",
        "Exile Undead",
        "Improved Invis vs Undead",
    ],
    'wizard': [
        "Invisibility to Undead",
        "Gravity Flux",
        "Supernova",
        "Enticement of Flame",
        "Translocate",
        "Atol's Spectral Shackles",
        "Atol`s Spectral Shackles",
        "Draught of Fire",
        "Pillar of Frost",
        "Tishan's Discord",
        "Tishan`s Discord",
        "Abscond",
        "Tears of Druzzil",
        "Translocate: Group",
        "Inferno of Al'Kabor",
        "Inferno of Al`Kabor",
        "Pillar of Lightning",
        "Thunderbold",
        "Draught of Jiva",
        "Improved Invisibility",
        "Plainsight",
        "Tears of Solusek",
        "Markar's Discord",
        "Markar`s Discord",
        "Retribution of Al'Kabor",
        "Retribution of Al`Kabor",
        "Evacuate",
        "Eye of Tallon",
        "Pillar of Flame",
        "Manasink",
        "Tears of Prexus",
        "Flaming Sword of Xuzl",
        "Invert Gravity",
        "Vengeance of Al'Kabor",
        "Vengeance of Al`Kabor",
        "Disintegrate",
        "Hsagra's Wrath",
        "Hsagra`s Wrath",
        "Ice Spear of Solist",
        "Lure of Ice",
        "Porlos' Fury",
        "Porlos` Fury",
        "Sunstrike",
        "Winds of Gelid",
        "Ice Comet",
        "Great Divide Portal",
        "Cobalt Scar Portal",
        "Wakening Lands Portal",
    ],
    'shaman': [
        "Ultravision",
        "Tumultuous Strength",
        "Blast of Poison",
        "Spirit Quickening",
        "Talisman of Jasinth",
        "Insidious Decay",
        "Spirit of Scale",
        "Cripple",
        "Talisman of Shadoo",
        "Cannibalize III",
        "Shroud of the Spirits",
        "Form of the Great Bear",
        "Spirit of the Howler",
        "Torrent of Poison",
        "Acumen",
        "Bane of Nife",
        "Talisman of the Brute",
        "Talisman of the Cat",
        "Cannibalize IV",
        "Talisman of the Rhino",
        "Talisman of the Serpent",
        "Tigir's Insects",
        "Tigir`s Insects",
        "Pox of Bertoxxulous",
        "Talisman of the Raptor",
        "Voice of the Berserker",
        "Avatar",
        "Focus of Spirit",
        "Malo",
        "Primal Avatar",
        "Torpor",
    ],
    'paladin': [
        "Flame of Light",
        "Wave of Healing",
        "Divine Strength",
        "Yaulp IV",
    ],
    'bard': [
        "Melody of Ervaj",
        "Occlusion of Sound",
        "Composition of Ervaj",
    ],
    'ranger': [
        "Call of Earth",
        "Call of Flame",
        "Call of Fire",
        "Call of the Predator",
    ],
    'shadow knight': [
        "Shroud of Hate",
        "Shroud of Pain",
        "Summon Corpse",
        "Shroud of Death",
        "Shroud of Undeath",
        "Death Peace",
    ]

}
