"""
Taken from running python parse_spell_mules.py --count
"""

['Acumen', 8]
['Aegis', 2]
['Aegis of Ro', 22]
['Aegolism', 20]
['Arch Lich', 21]
['Asphyxiate', 20]
['Avatar', 4]
['Bandoleer of Luclin', 12]
['Banishment', 22]
['Banishment of Shadows', 1]
['Blizzard', 16]
['Boon of the Garou', 2]
['Breath of Karana', 6]
['Call of Earth', 2]
['Call of Fire', 2]
['Call of the Predator', 20]
['Cannibalize IV', 2]
['Chill Bones', 4]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Great Divide', 1]
['Circle of Wakening Lands', 3]
['Composition of Ervaj', 14]
['Conjure Corpse', 1]
['Corporeal Empathy', 1]
['Death Pact', 3]
['Death Peace', 14]
['Defoliation', 2]
['Demi Lich', 3]
['Devouring Darkness', 3]
['Divine Strength', 23]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Enforced Reverence', 9]
['Enlightenment', 2]
['Enslave Death', 3]
['Enticement of Flame', 2]
['Entrapping Roots', 19]
['Evacuate', 5]
['Exile Undead', 4]
['Flame of Light', 1]
['Flaming Sword of Xuzl', 18]
['Focus of Spirit', 22]
['Form of the Howler', 1]
['Gift of Brilliance', 6]
['Gift of Insight', 4]
['Girdle of Karana', 6]
['Greater Vocaration: Air', 44]
['Greater Vocaration: Fire', 1]
['Greater Vocaration: Water', 4]
['Harmshield', 1]
['Heroic Bond', 14]
['Ice Spear of Solist', 16]
['Improved Invisibility', 1]
['Inferno of Al`Kabor', 4]
['Infusion', 12]
['Invert Gravity', 5]
['Legacy of Spike', 1]
['Mala', 38]
['Malignant Dead', 1]
['Malo', 1]
['Manasink', 1]
['Manastorm', 45]
['Markar`s Discord', 10]
['Monster Summoning III', 8]
["Naltron's Mark", 1]
['Nature Walkers Behest', 1]
['Occlusion of Sound', 1]
['Pillar of Frost', 1]
['Pillar of Lightning', 2]
['Protection of the Glades', 4]
['Quivering Veil of Xarn', 13]
['Reckoning', 1]
['Retribution of Al`Kabor', 3]
['Shroud of Death', 3]
['Shroud of Pain', 2]
['Spirit of Oak', 6]
['Spirit of Scale', 1]
['Talisman of Jasinth', 2]
['Talisman of the Serpent', 1]
['Tears of Druzzil', 1]
['Tears of Prexus', 17]
['Thrall of Bones', 1]
['Tigir`s Insects', 11]
['Trepidation', 1]
['Trucidation', 8]
['Tunare`s Request', 12]
['Velocity', 3]
['Vengeance of Al`Kabor', 12]
['Visions of Grandeur', 1]
['Vocarate: Water', 7]
['Voice of the Berserker', 5]
['Wakening Lands Portal', 1]
['Wave of Healing', 1]
['Wind of Tishanian', 29]
['Word of Redemption', 6]
['Wrath of the Elements', 3]
