['Acumen', 5]
['Aegis of Ro', 17]
['Aegolism', 18]
['Allure', 4]
['Arch Lich', 18]
['Asphyxiate', 3]
['Atol`s Spectral Shackles', 4]
['Bandoleer of Luclin', 11]
['Banishment', 2]
['Berserker Strength', 1]
['Blanket of Forgetfulness', 9]
['Blaze', 1]
['Blizzard', 11]
['Bond of Death', 4]
['Breath of Karana', 3]
['Bristlebane`s Bundle', 1]
['Burnout IV', 1]
['Cackling Bones', 3]
['Call of Bones', 9]
['Call of the Hero', 1]
['Call of the Predator', 19]
['Cannibalize III', 5]
['Cast Force', 1]
['Celestial Healing', 1]
['Chilling Embrace', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 7]
['Circle of Summer', 3]
['Circle of Wakening Lands', 2]
['Circle of Winter', 1]
['Color Shift', 1]
['Color Skew', 12]
['Color Slant', 6]
['Column of Fire', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 4]
['Convergence', 3]
['Cornucopia', 11]
['Corporeal Empathy', 4]
['Dead Man Floating', 8]
['Death Pact', 4]
['Death Peace', 19]
['Defoliation', 2]
['Dementia', 4]
['Demi Lich', 1]
['Divine Strength', 14]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Endure Magic', 1]
['Energy Storm', 1]
['Enlightenment', 7]
['Enslave Death', 2]
['Enticement of Flame', 7]
['Entrapping Roots', 2]
['Everfount', 15]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Feedback', 8]
["Fire Spiral of Al'Kabor", 4]
['Fist of Karana', 1]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 8]
['Focus of Spirit', 18]
["Force Spiral of Al'Kabor", 1]
['Form of the Howler', 1]
['Gift of Insight', 1]
['Gift of Xev', 3]
['Gravity Flux', 9]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 5]
['Greater Conjuration: Fire', 5]
['Greater Conjuration: Water', 14]
['Greater Summoning: Earth', 1]
['Greater Vocaration: Air', 28]
['Greater Vocaration: Fire', 2]
['Harmshield', 3]
['Haunting Corpse', 4]
['Heroic Bond', 16]
['Hungry Earth', 7]
['Ice Spear of Solist', 13]
['Inferno of Al`Kabor', 5]
['Infusion', 9]
['Insipid Weakness', 14]
['Intensify Death', 3]
['Invert Gravity', 1]
['Invoke Death', 5]
['Invoke Shadow', 5]
['Lava Storm', 8]
['Lesser Conjuration: Water', 4]
['Lich', 8]
['Lightning Storm', 3]
['Mala', 25]
['Malignant Dead', 3]
['Mana Sieve', 19]
['Manastorm', 23]
['Mark of Karn', 1]
['Markar`s Discord', 7]
['Mesmerization', 1]
['Mind Wipe', 5]
['Monster Summoning III', 12]
['Paralyzing Earth', 30]
['Pillage Enchantment', 6]
['Pillar of Fire', 10]
['Pillar of Frost', 6]
['Pillar of Lightning', 7]
['Protection of the Glades', 1]
['Quiver of Marr', 3]
['Radiant Visage', 6]
['Rapture', 1]
['Regrowth of the Grove', 1]
['Renew Bones', 4]
['Reoccurring Amnesia', 17]
['Restless Bones', 1]
['Retribution of Al`Kabor', 2]
['Scale of Wolf', 1]
['Scars of Sigil', 5]
['Shiftless Deeds', 10]
["Shock Spiral of Al'Kabor", 4]
['Shroud of Death', 2]
['Spirit of Scale', 2]
['Splurt', 3]
['Stun Command', 1]
['Succor', 1]
['Summon Dead', 2]
['Summon: Muzzle of Mardu', 1]
['Supernova', 1]
['Talisman of Jasinth', 4]
['Tears of Prexus', 12]
['The Unspoken Word', 1]
['Theft of Thought', 1]
['Thrall of Bones', 5]
['Thunderclap', 7]
['Tigir`s Insects', 13]
['Trucidation', 2]
['Tunare`s Request', 14]
['Upheaval', 6]
['Vampiric Curse', 5]
['Velocity', 2]
['Vengeance of Al`Kabor', 11]
['Vocarate: Water', 15]
['Wake of Tranquility', 3]
['Wind of Tishanian', 23]
["Wrath of Ap'Sagor", 8]
['Wrath of the Elements', 6]
['Yaulp IV', 1]
