['Acumen', 7]
['Aegis of Ro', 17]
['Aegolism', 18]
['Allure', 2]
['Arch Lich', 19]
['Asphyxiate', 3]
['Atol`s Spectral Shackles', 4]
['Avatar', 2]
['Bandoleer of Luclin', 11]
['Banishment', 2]
['Banishment of Shadows', 1]
['Berserker Strength', 1]
['Blanket of Forgetfulness', 3]
['Blast of Poison', 1]
['Blaze', 1]
['Blizzard', 11]
['Bond of Death', 2]
['Breath of Karana', 3]
['Bristlebane`s Bundle', 1]
['Burnout IV', 1]
['Cackling Bones', 3]
['Call of Bones', 2]
['Call of the Hero', 1]
['Call of the Predator', 20]
['Cannibalize III', 6]
['Cannibalize IV', 2]
['Cast Force', 1]
['Celestial Healing', 1]
['Chilling Embrace', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 1]
['Circle of Summer', 3]
['Circle of Wakening Lands', 2]
['Circle of Winter', 3]
['Color Skew', 5]
['Color Slant', 6]
['Column of Fire', 1]
['Column of Lightning', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Convergence', 6]
['Corporeal Empathy', 4]
['Cripple', 1]
['Dead Man Floating', 5]
['Death Pact', 4]
['Death Peace', 19]
['Defoliation', 6]
['Dementia', 4]
['Demi Lich', 1]
['Disintegrate', 1]
['Divine Strength', 14]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Endure Magic', 1]
['Energy Storm', 1]
['Enlightenment', 7]
['Enslave Death', 2]
['Enticement of Flame', 7]
['Entrapping Roots', 2]
['Evacuate', 3]
['Everfount', 2]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Feedback', 1]
["Fire Spiral of Al'Kabor", 4]
['Fist of Karana', 1]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 8]
['Focus of Spirit', 19]
["Force Spiral of Al'Kabor", 1]
['Form of the Howler', 1]
['Gift of Insight', 1]
['Gift of Xev', 3]
['Gravity Flux', 4]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 1]
['Greater Conjuration: Water', 4]
['Greater Summoning: Earth', 1]
['Greater Vocaration: Air', 28]
['Greater Vocaration: Fire', 2]
['Harmshield', 1]
['Haunting Corpse', 4]
['Heroic Bond', 16]
['Hungry Earth', 7]
['Ice Spear of Solist', 15]
['Improved Invisibility', 1]
['Inferno of Al`Kabor', 5]
['Infusion', 10]
['Insipid Weakness', 9]
['Intensify Death', 3]
['Invert Gravity', 3]
['Invoke Shadow', 1]
['Lava Storm', 8]
['Lich', 2]
['Lightning Storm', 4]
['Mala', 25]
['Malignant Dead', 3]
['Mana Sieve', 7]
['Manastorm', 23]
['Mark of Karn', 1]
['Markar`s Discord', 9]
['Mesmerization', 1]
['Mind Wipe', 1]
['Monster Summoning III', 12]
['Paralyzing Earth', 23]
['Pillar of Fire', 7]
['Pillar of Frost', 7]
['Pillar of Lightning', 7]
['Project Lightning', 1]
['Protection of the Glades', 1]
['Quiver of Marr', 3]
['Quivering Veil of Xarn', 1]
['Rapture', 1]
['Reckoning', 1]
['Regrowth of the Grove', 1]
['Renew Bones', 4]
['Reoccurring Amnesia', 12]
['Restless Bones', 1]
['Retribution of Al`Kabor', 4]
['Scale of Wolf', 1]
['Scars of Sigil', 5]
['Shiftless Deeds', 3]
["Shock Spiral of Al'Kabor", 4]
['Shroud of Death', 2]
['Spirit of Scale', 3]
['Spirit of the Howler', 2]
['Splurt', 3]
['Stun Command', 1]
['Succor', 1]
['Summon Dead', 2]
['Summon: Muzzle of Mardu', 1]
['Sunstrike', 1]
['Talisman of Jasinth', 5]
['Tears of Prexus', 13]
['The Unspoken Word', 1]
['Theft of Thought', 1]
['Thrall of Bones', 6]
['Thunderclap', 11]
['Tigir`s Insects', 15]
['Trucidation', 2]
['Tunare`s Request', 14]
['Upheaval', 6]
['Vampiric Curse', 5]
['Velocity', 2]
['Vengeance of Al`Kabor', 12]
['Vocarate: Water', 15]
['Voice of the Berserker', 1]
['Wake of Tranquility', 3]
['Wind of Tishanian', 23]
['Word of Redemption', 1]
["Wrath of Ap'Sagor", 8]
['Wrath of the Elements', 6]
['Yaulp IV', 1]
