['Acumen', 4]
['Aegis of Ro', 17]
['Aegolism', 14]
['Arch Lich', 15]
['Asphyxiate', 1]
['Atol`s Spectral Shackles', 4]
['Bandoleer of Luclin', 10]
['Banishment', 1]
['Bedlam', 1]
['Blanket of Forgetfulness', 6]
['Blaze', 1]
['Blizzard', 11]
['Bond of Death', 3]
['Breath of Karana', 1]
['Cackling Bones', 1]
['Call of Bones', 8]
['Call of the Predator', 18]
['Cannibalize III', 4]
['Cannibalize IV', 1]
['Chords of Dissonance', 4]
['Circle of Force', 6]
['Circle of Summer', 1]
['Circle of Wakening Lands', 1]
['Color Skew', 10]
['Color Slant', 3]
['Column of Fire', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 4]
['Cornucopia', 11]
['Corporeal Empathy', 4]
['Dead Man Floating', 9]
['Death Peace', 19]
['Dementia', 1]
['Divine Strength', 14]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Endure Magic', 1]
['Enlightenment', 4]
['Enslave Death', 3]
['Enticement of Flame', 7]
['Evacuate', 1]
['Everfount', 15]
['Feedback', 4]
["Fire Spiral of Al'Kabor", 3]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 7]
['Focus of Spirit', 17]
["Force Spiral of Al'Kabor", 1]
['Gift of Xev', 2]
['Gravity Flux', 6]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 5]
['Greater Conjuration: Fire', 5]
['Greater Conjuration: Water', 14]
['Greater Summoning: Earth', 1]
['Greater Vocaration: Air', 27]
['Greater Vocaration: Fire', 2]
['Harmshield', 1]
['Haunting Corpse', 3]
['Heroic Bond', 16]
['Hungry Earth', 5]
['Ice Spear of Solist', 12]
['Inferno of Al`Kabor', 6]
['Infusion', 7]
['Insipid Weakness', 12]
['Intensify Death', 2]
['Invert Gravity', 2]
['Invoke Death', 4]
['Invoke Shadow', 3]
['Lava Storm', 7]
['Lesser Conjuration: Water', 4]
['Lich', 7]
['Lightning Storm', 2]
['Mala', 22]
['Malignant Dead', 1]
['Mana Sieve', 13]
['Manastorm', 23]
['Markar`s Discord', 7]
['Mind Wipe', 2]
['Monster Summoning III', 10]
['Paralyzing Earth', 27]
['Pillage Enchantment', 3]
['Pillar of Fire', 8]
['Pillar of Frost', 6]
['Pillar of Lightning', 9]
['Quiver of Marr', 1]
['Radiant Visage', 1]
['Rapture', 1]
['Renew Bones', 3]
['Reoccurring Amnesia', 14]
['Retribution of Al`Kabor', 2]
["Ro's Fiery Sundering", 1]
['Scale of Wolf', 1]
['Shiftless Deeds', 8]
["Shock Spiral of Al'Kabor", 3]
['Shroud of Death', 2]
['Spirit of the Howler', 1]
['Succor', 1]
['Summon Dead', 2]
['Summon: Muzzle of Mardu', 1]
['Talisman of Jasinth', 4]
['Tears of Druzzil', 2]
['Tears of Prexus', 12]
['Thunderclap', 5]
['Tigir`s Insects', 12]
['Tunare`s Request', 14]
['Unfailing Reverence', 1]
['Upheaval', 3]
['Vampiric Curse', 3]
['Velocity', 2]
['Vengeance of Al`Kabor', 11]
['Vocarate: Water', 14]
['Wake of Tranquility', 1]
['Wind of Tishanian', 20]
["Wrath of Ap'Sagor", 7]
['Wrath of the Elements', 5]
