"""Taken from running python parse_spell_mules.py, this is the output
on the top.
"""

['Acumen', 8]
['Aegis', 2]
['Aegis of Ro', 24]
['Aegolism', 21]
['Arch Lich', 21]
['Asphyxiate', 21]
['Avatar', 4]
['Bandoleer of Luclin', 14]
['Banishment', 23]
['Banishment of Shadows', 1]
['Blizzard', 16]
['Boon of the Garou', 2]
['Breath of Karana', 5]
['Bristlebane's Bundle', 1]
['Call of Earth', 2]
['Call of Fire', 3]
['Call of the Predator', 21]
['Cannibalize IV', 2]
['Chill Bones', 4]
['Circle of Cobalt Scar', 1]
['Circle of Great Divide', 1]
['Circle of Wakening Lands', 3]
['Composition of Ervaj', 14]
['Conjure Corpse', 1]
['Corporeal Empathy', 1]
['Death Pact', 3]
['Death Peace', 15]
['Defoliation', 2]
['Demi Lich', 3]
['Devouring Darkness', 3]
['Divine Strength', 23]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Enforced Reverence', 9]
['Enlightenment', 3]
['Enslave Death', 4]
['Enticement of Flame', 3]
['Entrapping Roots', 21]
['Evacuate', 5]
['Exile Undead', 3]
['Fixation of Ro', 1]
['Flame of Light', 1]
['Flaming Sword of Xuzl', 18]
['Focus of Spirit', 21]
['Frost', 1]
['Gift of Brilliance', 6]
['Gift of Insight', 5]
['Gift of Xev', 1]
['Girdle of Karana', 5]
['Greater Vocaration: Air', 45]
['Greater Vocaration: Fire', 2]
['Greater Vocaration: Water', 4]
['Harmshield', 1]
['Heroic Bond', 14]
['Ice Spear of Solist', 16]
['Improved Invisibility', 2]
['Inferno of Al`Kabor', 4]
['Infusion', 11]
['Invert Gravity', 5]
['Legacy of Spike', 1]
['Legacy of Thorn', 1]
['Mala', 39]
['Malignant Dead', 1]
['Manasink', 1]
['Manastorm', 47]
['Markar`s Discord', 10]
['Monster Summoning III', 8]
['Nature Walkers Behest', 2]
['Occlusion of Sound', 1]
['Pillar of Frost', 1]
['Pillar of Lightning', 2]
['Protection of the Glades', 5]
['Quivering Veil of Xarn', 13]
['Rage of Zomm', 2]
['Retribution of Al`Kabor', 2]
['Scars of Sigil', 2]
['Shroud of Death', 4]
['Shroud of Pain', 3]
['Spirit of Oak', 7]
['Talisman of Jasinth', 2]
['Tears of Druzzil', 2]
['Tears of Prexus', 17]
['Thrall of Bones', 1]
['Tigir`s Insects', 11]
['Torpor', 1]
['Trucidation', 8]
['Tunare`s Request', 13]
['Upheaval', 1]
['Velocity', 5]
['Vengeance of Al`Kabor', 12]
['Vocarate: Fire', 1]
['Vocarate: Water', 8]
['Voice of the Berserker', 5]
['Wakening Lands Portal', 1]
['Wave of Healing', 1]
['Wind of Tishanian', 29]
['Word of Redemption', 7]
['Wrath of the Elements', 5]
