['Acumen', 2]
['Aegis of Ro', 17]
['Aegolism', 14]
['Arch Lich', 15]
['Asphyxiate', 1]
['Atol`s Spectral Shackles', 2]
['Bandoleer of Luclin', 10]
['Banishment', 1]
['Blanket of Forgetfulness', 6]
['Blaze', 1]
['Blizzard', 12]
['Bond of Death', 3]
['Breath of Karana', 1]
['Call of Bones', 8]
['Call of the Predator', 18]
['Cannibalize III', 3]
['Chords of Dissonance', 4]
['Circle of Force', 5]
['Circle of Summer', 3]
['Circle of Wakening Lands', 1]
['Circle of Winter', 1]
['Color Skew', 10]
['Color Slant', 3]
['Column of Fire', 1]
['Composition of Ervaj', 14]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 3]
['Cornucopia', 10]
['Corporeal Empathy', 4]
['Dead Man Floating', 9]
['Death Peace', 17]
['Defoliation', 1]
['Divine Strength', 14]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Endure Magic', 1]
['Enlightenment', 3]
['Enslave Death', 3]
['Enticement of Flame', 6]
['Evacuate', 1]
['Everfount', 14]
['Feedback', 4]
["Fire Spiral of Al'Kabor", 3]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 6]
['Focus of Spirit', 16]
['Gift of Xev', 2]
['Gravity Flux', 4]
['Greater Conjuration: Air', 4]
['Greater Conjuration: Fire', 4]
['Greater Conjuration: Water', 13]
['Greater Summoning: Earth', 1]
['Greater Vocaration: Air', 27]
['Greater Vocaration: Fire', 2]
['Harmshield', 1]
['Haunting Corpse', 1]
['Heroic Bond', 16]
['Hungry Earth', 5]
['Ice Spear of Solist', 11]
['Inferno of Al`Kabor', 5]
['Infusion', 7]
['Insipid Weakness', 12]
['Intensify Death', 2]
['Invert Gravity', 1]
['Invoke Death', 4]
['Invoke Shadow', 2]
['Lava Storm', 6]
['Lesser Conjuration: Water', 3]
['Lich', 7]
['Lightning Storm', 1]
['Mala', 22]
['Mana Sieve', 12]
['Manastorm', 23]
['Markar`s Discord', 6]
['Mind Wipe', 2]
['Monster Summoning III', 10]
['Paralyzing Earth', 26]
['Pillage Enchantment', 3]
['Pillar of Fire', 7]
['Pillar of Frost', 4]
['Pillar of Lightning', 8]
['Quiver of Marr', 3]
['Radiant Visage', 1]
['Rapture', 1]
['Reckoning', 1]
['Renew Bones', 3]
['Reoccurring Amnesia', 14]
['Retribution of Al`Kabor', 1]
["Ro's Fiery Sundering", 1]
['Scale of Wolf', 1]
['Scars of Sigil', 1]
['Shiftless Deeds', 8]
["Shock Spiral of Al'Kabor", 2]
['Spirit of Scale', 2]
['Splurt', 1]
['Succor', 1]
['Summon Dead', 1]
['Summon: Muzzle of Mardu', 1]
['Talisman of Jasinth', 3]
['Tears of Druzzil', 2]
['Tears of Prexus', 11]
['Thrall of Bones', 1]
['Thunderclap', 4]
['Tigir`s Insects', 11]
['Tunare`s Request', 14]
['Unfailing Reverence', 1]
['Upheaval', 4]
['Vampiric Curse', 3]
['Velocity', 2]
['Vengeance of Al`Kabor', 10]
['Vocarate: Water', 14]
['Wake of Tranquility', 1]
['Wind of Tishanian', 20]
["Wrath of Ap'Sagor", 6]
['Wrath of the Elements', 5]
