['Acumen', 9]
['Aegis of Ro', 16]
['Aegolism', 16]
['Allure', 8]
['Arch Lich', 24]
['Asphyxiate', 6]
['Augment', 1]
['Avatar', 2]
['Bandoleer of Luclin', 9]
['Banishment', 8]
['Berserker Strength', 1]
['Blanket of Forgetfulness', 10]
['Blast of Poison', 2]
['Blaze', 1]
['Blizzard', 11]
['Bond of Death', 13]
['Boon of the Garou', 3]
['Breath of Karana', 7]
['Bristlebane`s Bundle', 1]
['Bulwark of Faith', 1]
['Cackling Bones', 4]
['Call of the Predator', 22]
['Cannibalize III', 2]
['Cannibalize IV', 2]
['Celestial Healing', 1]
['Chill Bones', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 7]
['Circle of Wakening Lands', 2]
['Color Shift', 3]
['Color Skew', 10]
['Column of Fire', 1]
['Column of Lightning', 2]
['Composition of Ervaj', 16]
['Conjure Corpse', 1]
['Corporeal Empathy', 6]
['Death Pact', 1]
['Death Peace', 18]
['Dementia', 2]
['Demi Lich', 1]
['Divine Strength', 15]
['Draught of Jiva', 3]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Energy Storm', 1]
['Enforced Reverence', 2]
['Enlightenment', 8]
['Enslave Death', 1]
['Enticement of Flame', 8]
['Entrapping Roots', 6]
['Evacuate', 2]
['Everfount', 2]
['Exile Undead', 3]
['Eye of Tallon', 2]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 13]
['Focus of Spirit', 19]
["Force Spiral of Al'Kabor", 1]
['Fortitude', 1]
['Gift of Insight', 3]
['Gravity Flux', 7]
['Greater Conjuration: Air', 4]
['Greater Conjuration: Fire', 3]
['Greater Conjuration: Water', 1]
['Greater Summoning: Earth', 4]
['Greater Vocaration: Air', 24]
['Greater Vocaration: Fire', 1]
['Harmshield', 3]
['Haunting Corpse', 1]
['Heroic Bond', 15]
['Ice Spear of Solist', 19]
['Infusion', 11]
['Insipid Weakness', 12]
['Invert Gravity', 3]
['Invoke Death', 3]
['Lich', 3]
['Lure of Ice', 2]
['Mala', 21]
['Malignant Dead', 2]
['Mana Sieve', 15]
['Manastorm', 24]
['Markar`s Discord', 14]
['Mesmerization', 3]
['Mind Wipe', 11]
['Monster Summoning III', 8]
["Naltron's Mark", 1]
['Paralyzing Earth', 21]
['Pillage Enchantment', 4]
['Pillar of Fire', 3]
['Pillar of Lightning', 3]
['Project Lightning', 5]
['Protection of the Glades', 4]
['Quiver of Marr', 1]
['Quivering Veil of Xarn', 8]
['Rage of Zomm', 1]
['Reckoning', 1]
['Renew Bones', 6]
['Reoccurring Amnesia', 18]
['Retribution of Al`Kabor', 5]
['Scars of Sigil', 4]
['Shiftless Deeds', 7]
['Shroud of Death', 1]
['Stun Command', 2]
['Succor', 3]
['Summon Drink', 2]
['Summon Food', 1]
['Sunstrike', 1]
['Supernova', 1]
['Talisman of Jasinth', 4]
['Tears of Prexus', 18]
['Tepid Deeds', 3]
['The Unspoken Word', 1]
['Theft of Thought', 1]
['Thunderclap', 5]
['Tigir`s Insects', 12]
['Trepidation', 1]
['Trucidation', 7]
['Tunare`s Request', 16]
['Turning of the Unnatural', 1]
['Vampiric Curse', 3]
['Velocity', 2]
['Vengeance of Al`Kabor', 15]
['Vocarate: Water', 14]
['Voice of the Berserker', 1]
['Wake of Tranquility', 1]
['Wave of Healing', 1]
['Wind of Tishanian', 23]
['Winds of Gelid', 1]
["Wrath of Ap'Sagor", 3]
['Wrath of the Elements', 4]
['Yaulp IV', 3]
['Zumaik`s Animation', 1]
