['Acumen', 5]
['Aegis of Ro', 18]
['Aegolism', 18]
['Allure', 2]
['Arch Lich', 18]
['Asphyxiate', 3]
['Atol`s Spectral Shackles', 4]
['Bandoleer of Luclin', 11]
['Banishment', 2]
['Blanket of Forgetfulness', 8]
['Blaze', 1]
['Blizzard', 11]
['Bond of Death', 3]
['Breath of Karana', 3]
['Bristlebane`s Bundle', 1]
['Cackling Bones', 2]
['Call of Bones', 8]
['Call of the Hero', 1]
['Call of the Predator', 19]
['Cannibalize III', 5]
['Cannibalize IV', 2]
['Celestial Healing', 1]
['Chilling Embrace', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 6]
['Circle of Summer', 2]
['Circle of Wakening Lands', 2]
['Color Skew', 11]
['Color Slant', 5]
['Column of Fire', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 4]
['Convergence', 3]
['Cornucopia', 11]
['Corporeal Empathy', 4]
['Dead Man Floating', 9]
['Death Pact', 4]
['Death Peace', 19]
['Defoliation', 2]
['Dementia', 4]
['Demi Lich', 1]
['Divine Strength', 14]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Endure Magic', 1]
['Enlightenment', 7]
['Enslave Death', 3]
['Enticement of Flame', 7]
['Entrapping Roots', 2]
['Everfount', 15]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Feedback', 5]
["Fire Spiral of Al'Kabor", 3]
['Fist of Karana', 1]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 8]
['Focus of Spirit', 19]
["Force Spiral of Al'Kabor", 1]
['Form of the Howler', 1]
['Gift of Insight', 1]
['Gift of Xev', 2]
['Gravity Flux', 6]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 5]
['Greater Conjuration: Fire', 5]
['Greater Conjuration: Water', 14]
['Greater Summoning: Earth', 1]
['Greater Vocaration: Air', 28]
['Greater Vocaration: Fire', 2]
['Harmshield', 2]
['Haunting Corpse', 3]
['Heroic Bond', 16]
['Hungry Earth', 6]
['Ice Spear of Solist', 13]
['Inferno of Al`Kabor', 6]
['Infusion', 9]
['Insipid Weakness', 12]
['Intensify Death', 2]
['Invert Gravity', 2]
['Invoke Death', 4]
['Invoke Shadow', 4]
['Lava Storm', 7]
['Lesser Conjuration: Water', 4]
['Lich', 7]
['Lightning Storm', 2]
['Mala', 24]
['Malignant Dead', 2]
['Mana Sieve', 16]
['Manastorm', 24]
['Mark of Karn', 1]
['Markar`s Discord', 7]
['Mind Wipe', 2]
['Monster Summoning III', 12]
['Nature Walkers Behest', 1]
['Paralyzing Earth', 28]
['Pillage Enchantment', 4]
['Pillar of Fire', 9]
['Pillar of Frost', 6]
['Pillar of Lightning', 7]
['Protection of the Glades', 1]
['Quiver of Marr', 3]
['Radiant Visage', 2]
['Rapture', 1]
['Regrowth of the Grove', 1]
['Renew Bones', 3]
['Reoccurring Amnesia', 16]
['Restless Bones', 1]
['Retribution of Al`Kabor', 2]
['Scale of Wolf', 1]
['Scars of Sigil', 5]
['Shiftless Deeds', 9]
["Shock Spiral of Al'Kabor", 3]
['Shroud of Death', 2]
['Spirit of Scale', 2]
['Spirit of the Howler', 1]
['Splurt', 3]
['Stun Command', 1]
['Succor', 1]
['Summon Dead', 2]
['Summon: Muzzle of Mardu', 1]
['Talisman of Jasinth', 4]
['Tears of Druzzil', 1]
['Tears of Prexus', 12]
['The Unspoken Word', 1]
['Theft of Thought', 1]
['Thrall of Bones', 5]
['Thunderclap', 5]
['Tigir`s Insects', 13]
['Trucidation', 2]
['Tunare`s Request', 14]
['Upheaval', 5]
['Vampiric Curse', 4]
['Velocity', 2]
['Vengeance of Al`Kabor', 11]
['Vocarate: Water', 15]
['Wake of Tranquility', 3]
['Wind of Tishanian', 23]
["Wrath of Ap'Sagor", 7]
['Wrath of the Elements', 6]
['Yaulp IV', 1]
