['Acumen', 8]
['Aegis of Ro', 17]
['Aegolism', 18]
['Allure', 7]
['Arch Lich', 21]
['Asphyxiate', 6]
['Augmentation of Death', 1]
['Avatar', 1]
['Bandoleer of Luclin', 8]
['Banishment', 3]
['Banshee Aura', 1]
['Blanket of Forgetfulness', 3]
['Blast of Poison', 1]
['Blaze', 1]
['Blizzard', 10]
['Boltran`s Animation', 1]
['Bond of Death', 7]
['Breath of Karana', 3]
['Cackling Bones', 5]
['Call of the Hero', 1]
['Call of the Predator', 21]
['Cannibalize IV', 2]
['Cast Force', 1]
['Chill Bones', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 3]
['Circle of Wakening Lands', 2]
['Color Skew', 9]
['Color Slant', 1]
['Column of Fire', 1]
['Column of Lightning', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Earth', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 1]
['Conjure Corpse', 1]
['Cornucopia', 1]
['Corporeal Empathy', 3]
['Dead Man Floating', 8]
['Death Peace', 20]
['Divine Strength', 15]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Energy Storm', 1]
['Enlightenment', 10]
['Enticement of Flame', 6]
['Entrapping Roots', 1]
['Everfount', 3]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Feedback', 4]
["Fire Spiral of Al'Kabor", 4]
['Fist of Karana', 1]
['Flame Arc', 2]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 10]
['Focus of Spirit', 18]
["Force Spiral of Al'Kabor", 1]
['Gift of Brilliance', 3]
['Gift of Insight', 4]
['Gravity Flux', 3]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 4]
['Greater Conjuration: Fire', 4]
['Greater Conjuration: Water', 9]
['Greater Summoning: Earth', 2]
['Greater Vocaration: Air', 25]
['Greater Vocaration: Fire', 2]
['Harmshield', 3]
['Heroic Bond', 12]
['Hungry Earth', 1]
['Ice Spear of Solist', 19]
['Improved Invisibility', 1]
['Infusion', 11]
['Insipid Weakness', 11]
['Invoke Death', 1]
['Lava Storm', 8]
['Lich', 4]
['Lightning Storm', 4]
['Mala', 23]
['Mana Sieve', 13]
['Manastorm', 23]
['Markar`s Discord', 12]
['Mind Wipe', 3]
['Monster Summoning III', 12]
['Paralyzing Earth', 34]
['Pillage Enchantment', 2]
['Pillar of Fire', 7]
['Pillar of Lightning', 2]
['Project Lightning', 1]
['Protection of the Glades', 1]
['Quiver of Marr', 2]
['Quivering Veil of Xarn', 3]
['Renew Bones', 2]
['Reoccurring Amnesia', 15]
['Resist Magic', 1]
['Restless Bones', 1]
['Retribution of Al`Kabor', 4]
['Scars of Sigil', 1]
['Shiftless Deeds', 4]
["Shock Spiral of Al'Kabor", 4]
['Shroud of Death', 1]
['Spirit of the Howler', 2]
['Splurt', 1]
['Stun Command', 1]
['Succor', 1]
['Summon Dead', 2]
['Supernova', 1]
['Surge of Enfeeblement', 1]
['Talisman of Jasinth', 1]
['Tears of Prexus', 14]
['Theft of Thought', 1]
['Thunderclap', 12]
['Tigir`s Insects', 15]
['Translocate', 1]
['Trepidation', 1]
['Trucidation', 4]
['Tunare`s Request', 14]
['Upheaval', 2]
['Vampiric Curse', 2]
['Velocity', 2]
['Vengeance of Al`Kabor', 13]
['Vocarate: Water', 12]
['Wind of Tishanian', 26]
['Word of Restoration', 1]
["Wrath of Ap'Sagor", 8]
['Wrath of the Elements', 6]
