['Acumen', 9]
['Aegis of Ro', 18]
['Aegolism', 14]
['Allure', 11]
['Arch Lich', 21]
['Asphyxiate', 10]
['Atol`s Spectral Shackles', 1]
['Augment', 1]
['Avatar', 2]
['Bandoleer of Luclin', 7]
['Banishment', 7]
['Berserker Strength', 2]
['Blanket of Forgetfulness', 13]
['Blast of Poison', 2]
['Blaze', 1]
['Blizzard', 9]
['Bond of Death', 16]
['Bonds of Tunare', 1]
['Boon of the Garou', 4]
['Breath of Karana', 8]
['Bulwark of Faith', 1]
['Burnout IV', 1]
['Cackling Bones', 4]
['Call of Earth', 1]
['Call of Fire', 1]
['Call of the Predator', 21]
['Cannibalize III', 1]
['Cannibalize IV', 2]
['Cast Force', 1]
['Chill Bones', 5]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 9]
['Circle of Summer', 1]
['Circle of Wakening Lands', 2]
['Clarity II', 1]
['Color Shift', 4]
['Color Skew', 11]
['Column of Fire', 1]
['Column of Lightning', 4]
['Composition of Ervaj', 16]
['Conjure Corpse', 1]
['Corporeal Empathy', 3]
['Death Peace', 16]
['Defoliation', 1]
['Demi Lich', 1]
['Devouring Darkness', 2]
['Divine Strength', 17]
['Draught of Jiva', 3]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 2]
['Energy Storm', 2]
['Enforced Reverence', 3]
['Enlightenment', 8]
['Enslave Death', 2]
['Enticement of Flame', 5]
['Entrapping Roots', 9]
['Evacuate', 3]
['Everfount', 2]
['Exile Undead', 3]
['Eye of Tallon', 4]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 14]
['Focus of Spirit', 19]
["Force Spiral of Al'Kabor", 1]
['Form of the Howler', 1]
['Frost', 1]
['Gift of Brilliance', 1]
['Gift of Insight', 1]
['Gift of Pure Thought', 1]
['Girdle of Karana', 2]
['Gravity Flux', 13]
['Greater Conjuration: Air', 5]
['Greater Conjuration: Water', 3]
['Greater Vocaration: Air', 24]
['Greater Vocaration: Fire', 2]
['Greater Vocaration: Water', 1]
['Harmshield', 1]
['Heroic Bond', 14]
['Ice Spear of Solist', 17]
['Inferno of Al`Kabor', 4]
['Infusion', 12]
['Insidious Decay', 1]
['Insipid Weakness', 12]
['Invert Gravity', 4]
['Invoke Death', 3]
['Legacy of Thorn', 2]
['Lich', 6]
['Mala', 21]
['Malignant Dead', 2]
['Mana Sieve', 15]
['Manasink', 1]
['Manastorm', 23]
['Mark of Karn', 1]
['Markar`s Discord', 13]
['Mesmerization', 3]
['Mind Wipe', 12]
['Monster Summoning III', 6]
["Naltron's Mark", 1]
['Nature Walkers Behest', 1]
['Paralyzing Earth', 24]
['Pillage Enchantment', 4]
['Pillar of Fire', 4]
['Pillar of Lightning', 3]
['Project Lightning', 7]
['Protection of the Glades', 1]
['Quivering Veil of Xarn', 11]
['Radiant Visage', 1]
['Rage of Zomm', 1]
['Recant Magic', 1]
['Renew Bones', 7]
['Reoccurring Amnesia', 18]
['Retribution of Al`Kabor', 5]
['Shiftless Deeds', 7]
['Shroud of Death', 1]
['Spirit of Oak', 1]
['Splurt', 1]
['Strip Enchantment', 1]
['Stun Command', 1]
['Succor', 2]
['Summon Drink', 2]
['Summon Food', 1]
['Supernova', 2]
['Talisman of Jasinth', 4]
['Talisman of the Brute', 1]
['Talisman of the Rhino', 1]
['Tears of Druzzil', 1]
['Tears of Prexus', 19]
['Tepid Deeds', 4]
['Thrall of Bones', 2]
['Thunderclap', 6]
['Tigir`s Insects', 12]
['Trucidation', 8]
['Tunare`s Request', 16]
['Turning of the Unnatural', 1]
['Vampiric Curse', 3]
['Velocity', 2]
['Vengeance of Al`Kabor', 14]
['Vocarate: Water', 9]
['Voice of the Berserker', 2]
['Wind of Tishani', 1]
['Wind of Tishanian', 25]
['Winds of Gelid', 1]
["Wrath of Ap'Sagor", 3]
['Wrath of the Elements', 4]
