['Acumen', 9]
['Aegis of Ro', 16]
['Aegolism', 17]
['Allure', 16]
['Arch Lich', 23]
['Asphyxiate', 6]
['Augment', 1]
['Augmentation of Death', 1]
['Bandoleer of Luclin', 9]
['Banishment', 8]
['Berserker Strength', 2]
['Blanket of Forgetfulness', 11]
['Blast of Poison', 1]
['Blaze', 1]
['Blizzard', 11]
['Boltran`s Animation', 1]
['Bond of Death', 13]
['Boon of the Garou', 3]
['Breath of Karana', 7]
['Bristlebane`s Bundle', 1]
['Bulwark of Faith', 1]
['Cackling Bones', 4]
['Call of the Predator', 22]
['Cannibalize III', 1]
['Cannibalize IV', 2]
['Celestial Healing', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 6]
['Circle of Wakening Lands', 2]
['Color Shift', 3]
['Color Skew', 12]
['Column of Fire', 1]
['Column of Lightning', 1]
['Composition of Ervaj', 16]
['Conjure Corpse', 1]
['Cornucopia', 1]
['Corporeal Empathy', 5]
['Death Pact', 1]
['Death Peace', 20]
['Dementia', 2]
['Divine Strength', 15]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Enforced Reverence', 2]
['Enlightenment', 8]
['Enslave Death', 1]
['Enticement of Flame', 8]
['Entrapping Roots', 7]
['Evacuate', 1]
['Everfount', 3]
['Exile Undead', 2]
['Extinguish Fatigue', 1]
['Eye of Tallon', 2]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 10]
['Focus of Spirit', 18]
["Force Spiral of Al'Kabor", 1]
['Gift of Insight', 2]
['Gravity Flux', 7]
['Greater Conjuration: Air', 5]
['Greater Conjuration: Fire', 3]
['Greater Conjuration: Water', 12]
['Greater Summoning: Earth', 2]
['Greater Vocaration: Air', 24]
['Greater Vocaration: Fire', 1]
['Harmshield', 3]
['Haunting Corpse', 1]
['Heroic Bond', 15]
['Ice Spear of Solist', 16]
['Improved Invisibility', 1]
['Infusion', 12]
['Insipid Weakness', 14]
['Invert Gravity', 1]
['Invisibility to Undead', 1]
['Invoke Death', 3]
['Lich', 3]
['Mala', 21]
['Malignant Dead', 2]
['Mana Sieve', 15]
['Manastorm', 24]
['Markar`s Discord', 13]
['Mesmerization', 4]
['Mind Wipe', 9]
['Monster Summoning III', 8]
["Naltron's Mark", 1]
['Paralyzing Earth', 30]
['Pillage Enchantment', 5]
['Pillar of Fire', 3]
['Pillar of Flame', 1]
['Pillar of Lightning', 2]
['Project Lightning', 5]
['Protection of the Glades', 4]
['Quiver of Marr', 1]
['Quivering Veil of Xarn', 7]
['Radiant Visage', 3]
['Reckoning', 1]
['Regrowth of the Grove', 1]
['Renew Bones', 6]
['Reoccurring Amnesia', 20]
['Resist Magic', 1]
['Retribution of Al`Kabor', 5]
['Scars of Sigil', 4]
['Shiftless Deeds', 7]
['Shroud of Death', 2]
['Stun Command', 1]
['Succor', 3]
['Supernova', 3]
['Talisman of Jasinth', 2]
['Tears of Prexus', 15]
['Tepid Deeds', 2]
['The Unspoken Word', 1]
['Thunderclap', 4]
['Tigir`s Insects', 12]
['Trepidation', 1]
['Trucidation', 6]
['Tunare`s Request', 17]
['Vampiric Curse', 3]
['Velocity', 3]
['Vengeance of Al`Kabor', 14]
['Vocarate: Water', 13]
['Wave of Healing', 1]
['Wind of Tishanian', 24]
['Winds of Gelid', 1]
["Wrath of Ap'Sagor", 3]
['Wrath of the Elements', 4]
['Yaulp IV', 2]
['Zumaik`s Animation', 1]
