['Aegis of Ro', 16]
['Aegolism', 13]
['Arch Lich', 15]
['Atol`s Spectral Shackles', 1]
['Augmentation of Death', 1]
['Bandoleer of Luclin', 10]
['Blanket of Forgetfulness', 5]
['Blaze', 1]
['Blizzard', 12]
['Bond of Death', 2]
['Call of Bones', 7]
['Call of the Predator', 18]
['Cannibalize III', 1]
['Chords of Dissonance', 4]
['Circle of Force', 5]
['Circle of Summer', 2]
['Circle of Wakening Lands', 1]
['Color Skew', 8]
['Color Slant', 1]
['Column of Fire', 1]
['Composition of Ervaj', 14]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 2]
['Cornucopia', 8]
['Corporeal Empathy', 2]
['Dead Man Floating', 7]
['Death Peace', 17]
['Divine Strength', 14]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Endure Magic', 1]
['Enlightenment', 3]
['Enslave Death', 3]
['Enticement of Flame', 6]
['Evacuate', 1]
['Everfount', 12]
['Feedback', 2]
["Fire Spiral of Al'Kabor", 3]
['Flame Arc', 2]
['Flame of Light', 2]
['Flaming Sword of Xuzl', 6]
['Focus of Spirit', 14]
['Gift of Xev', 2]
['Gravity Flux', 4]
['Greater Conjuration: Air', 4]
['Greater Conjuration: Fire', 3]
['Greater Conjuration: Water', 11]
['Greater Vocaration: Air', 23]
['Greater Vocaration: Fire', 2]
['Harmshield', 1]
['Haunting Corpse', 1]
['Heroic Bond', 16]
['Hungry Earth', 5]
['Ice Spear of Solist', 10]
['Inferno of Al`Kabor', 5]
['Infusion', 7]
['Insipid Weakness', 11]
['Intensify Death', 2]
['Invert Gravity', 1]
['Invoke Death', 3]
['Invoke Shadow', 2]
['Lava Storm', 6]
['Lesser Conjuration: Water', 2]
['Lich', 6]
['Lightning Storm', 1]
['Mala', 19]
['Mana Sieve', 10]
['Manastorm', 21]
['Markar`s Discord', 6]
['Monster Summoning III', 10]
['Paralyzing Earth', 24]
['Pillage Enchantment', 1]
['Pillar of Fire', 7]
['Pillar of Frost', 3]
['Pillar of Lightning', 7]
['Quiver of Marr', 3]
['Rapture', 1]
['Reckoning', 1]
['Renew Bones', 2]
['Reoccurring Amnesia', 12]
['Retribution of Al`Kabor', 1]
['Scale of Wolf', 1]
['Scars of Sigil', 1]
['Shiftless Deeds', 6]
["Shock Spiral of Al'Kabor", 2]
['Spirit of Scale', 1]
['Summon Dead', 1]
['Summon: Muzzle of Mardu', 1]
['Talisman of Jasinth', 1]
['Tears of Druzzil', 2]
['Tears of Prexus', 9]
['Thunderclap', 4]
['Tigir`s Insects', 9]
['Tunare`s Request', 13]
['Unfailing Reverence', 1]
['Upheaval', 4]
['Vampiric Curse', 3]
['Velocity', 2]
['Vengeance of Al`Kabor', 10]
['Vocarate: Water', 14]
['Wake of Tranquility', 1]
['Wind of Tishanian', 11]
["Wrath of Ap'Sagor", 6]
['Wrath of the Elements', 5]
