"""Taken from running python parse_spell_mules.py, this is the output
on the top.
"""

['Acumen', 11]
['Aegis', 1]
['Aegis of Ro', 22]
['Aegolism', 18]
['Arch Lich', 17]
['Asphyxiate', 21]
['Augmentation of Death', 1]
['Avatar', 5]
['Bandoleer of Luclin', 14]
['Banishment', 25]
['Banishment of Shadows', 3]
['Blizzard', 16]
['Bonds of Tunare', 2]
['Breath of Karana', 7]
['Call of Earth', 2]
['Call of Fire', 1]
['Call of the Predator', 21]
['Chill Bones', 4]
['Circle of Cobalt Scar', 1]
['Circle of Great Divide', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 15]
['Conjure Corpse', 2]
['Corporeal Empathy', 2]
['Death Pact', 3]
['Death Peace', 17]
['Defoliation', 1]
['Demi Lich', 3]
['Devouring Darkness', 4]
['Divine Intervention', 1]
['Divine Strength', 24]
['Draught of Jiva', 2]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Enforced Reverence', 11]
['Enlightenment', 4]
['Enslave Death', 4]
['Enticement of Flame', 2]
['Entrapping Roots', 23]
['Evacuate', 9]
['Exile Undead', 1]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 21]
['Focus of Spirit', 19]
['Gift of Brilliance', 6]
['Gift of Insight', 7]
['Girdle of Karana', 7]
['Great Divide Portal', 1]
['Greater Vocaration: Air', 43]
['Greater Vocaration: Fire', 2]
['Greater Vocaration: Water', 3]
['Harmshield', 2]
['Heroic Bond', 18]
['Ice Spear of Solist', 17]
['Improved Invisibility', 1]
['Inferno of Al`Kabor', 1]
['Infusion', 11]
['Invert Gravity', 7]
['Largarn`s Lamentation', 1]
['Legacy of Spike', 1]
['Legacy of Thorn', 3]
['Lure of Ice', 3]
['Mala', 38]
['Malignant Dead', 1]
['Malo', 2]
['Manasink', 1]
['Manastorm', 44]
['Markar`s Discord', 11]
['Melody of Ervaj', 2]
['Monster Summoning III', 8]
['Nature Walkers Behest', 3]
['Occlusion of Sound', 5]
['Pillar of Frost', 1]
['Pillar of Lightning', 5]
['Pox of Bertoxxulous', 1]
['Protection of the Glades', 3]
['Quivering Veil of Xarn', 13]
['Rage of Zomm', 3]
['Retribution of Al`Kabor', 3]
['Scars of Sigil', 1]
['Shroud of Death', 4]
['Shroud of Pain', 3]
['Spirit Quickening', 1]
['Spirit of Oak', 9]
['Stun Command', 1]
['Talisman of the Raptor', 1]
['Tears of Prexus', 18]
['The Unspoken Word', 1]
['Theft of Thought', 1]
['Tigir`s Insects', 11]
['Translocate', 3]
['Trucidation', 7]
['Tunare`s Request', 12]
['Velocity', 4]
['Vengeance of Al`Kabor', 13]
['Visions of Grandeur', 1]
['Vocarate: Fire', 1]
['Vocarate: Water', 8]
['Voice of the Berserker', 6]
['Wake of Tranquility', 3]
['Wave of Healing', 5]
['Wind of Tishanian', 27]
['Winds of Gelid', 2]
['Word of Redemption', 9]
['Word of Souls', 1]
['Wrath of the Elements', 3]
['Yaulp IV', 3]
