['Acumen', 8]
['Aegis', 1]
['Aegis of Ro', 15]
['Aegolism', 16]
['Arch Lich', 19]
['Asphyxiate', 9]
['Bandoleer of Luclin', 7]
['Banishment', 8]
['Blast of Poison', 2]
['Blizzard', 10]
['Boon of the Garou', 4]
['Breath of Karana', 4]
['Call of Earth', 1]
['Call of the Predator', 21]
['Cannibalize IV', 2]
['Chill Bones', 5]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 14]
['Conjure Corpse', 2]
['Corporeal Empathy', 3]
['Death Pact', 3]
['Death Peace', 13]
['Demi Lich', 1]
['Devouring Darkness', 1]
['Divine Strength', 15]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 2]
['Energy Storm', 2]
['Enforced Reverence', 5]
['Enlightenment', 7]
['Enslave Death', 2]
['Enticement of Flame', 3]
['Entrapping Roots', 12]
['Evacuate', 4]
['Exile Undead', 2]
['Feedback', 1]
['Fixation of Ro', 1]
['Flame of Light', 1]
['Flaming Sword of Xuzl', 14]
['Focus of Spirit', 19]
['Gift of Brilliance', 1]
['Gift of Insight', 2]
['Gift of Pure Thought', 1]
['Girdle of Karana', 3]
['Greater Vocaration: Air', 24]
['Greater Vocaration: Fire', 1]
['Greater Vocaration: Water', 2]
['Harmshield', 1]
['Heroic Bond', 13]
['Ice Comet', 1]
['Ice Spear of Solist', 15]
['Improved Invisibility', 1]
['Inferno of Al`Kabor', 4]
['Infusion', 11]
['Invert Gravity', 5]
['Mala', 20]
['Malignant Dead', 1]
['Manasink', 2]
['Manastorm', 23]
['Markar`s Discord', 12]
['Monster Summoning III', 5]
['Nature Walkers Behest', 1]
['Pillar of Lightning', 2]
['Protection of the Glades', 1]
['Quivering Veil of Xarn', 11]
['Reckoning', 5]
['Retribution of Al`Kabor', 4]
['Stun Command', 1]
['Summon: Muzzle of Mardu', 1]
['Talisman of Jasinth', 3]
['Tears of Prexus', 17]
['Thrall of Bones', 1]
['Tigir`s Insects', 12]
['Trepidation', 1]
['Trucidation', 7]
['Tunare`s Request', 12]
['Upheaval', 1]
['Velocity', 2]
['Vengeance of Al`Kabor', 13]
['Vocarate: Water', 8]
['Voice of the Berserker', 3]
['Wake of Tranquility', 1]
['Wave of Healing', 1]
['Wind of Tishanian', 26]
['Word of Redemption', 3]
['Wrath of the Elements', 3]
['Yaulp IV', 1]
