['Acumen', 9]
['Aegis of Ro', 16]
['Aegolism', 16]
['Allure', 10]
['Arch Lich', 23]
['Asphyxiate', 5]
['Avatar', 1]
['Bandoleer of Luclin', 8]
['Banishment', 6]
['Banishment of Shadows', 1]
['Berserker Strength', 1]
['Blanket of Forgetfulness', 5]
['Blast of Poison', 1]
['Blaze', 1]
['Blizzard', 11]
['Boltran`s Animation', 1]
['Bond of Death', 12]
['Breath of Karana', 5]
['Cackling Bones', 6]
['Call of Bones', 3]
['Call of the Predator', 22]
['Cannibalize IV', 2]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 2]
['Circle of Wakening Lands', 2]
['Cobalt Scar Portal', 1]
['Color Skew', 11]
['Column of Fire', 1]
['Composition of Ervaj', 16]
['Conjuration: Air', 1]
['Conjuration: Earth', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 1]
['Convergence', 1]
['Cornucopia', 1]
['Corporeal Empathy', 5]
['Dead Man Floating', 4]
['Death Peace', 21]
['Divine Strength', 14]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Enforced Reverence', 1]
['Enlightenment', 11]
['Enslave Death', 1]
['Enticement of Flame', 8]
['Entrapping Roots', 4]
['Everfount', 3]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Eye of Tallon', 3]
['Feedback', 5]
['Fixation of Ro', 1]
['Flame Arc', 2]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 10]
['Focus of Spirit', 19]
["Force Spiral of Al'Kabor", 1]
['Fortitude', 1]
['Gravity Flux', 4]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 4]
['Greater Conjuration: Fire', 1]
['Greater Conjuration: Water', 10]
['Greater Summoning: Earth', 2]
['Greater Vocaration: Air', 24]
['Greater Vocaration: Fire', 1]
['Harmshield', 5]
['Haunting Corpse', 1]
['Heroic Bond', 15]
['Ice Spear of Solist', 17]
['Improved Invisibility', 2]
['Inferno of Al`Kabor', 1]
['Infusion', 12]
['Insipid Weakness', 12]
['Intensify Death', 1]
['Invoke Shadow', 3]
['Lich', 10]
['Mala', 23]
['Malignant Dead', 1]
['Mana Sieve', 15]
['Manasink', 1]
['Manastorm', 23]
['Markar`s Discord', 13]
['Mesmerization', 1]
['Mind Wipe', 5]
['Modulating Rod', 1]
['Monster Summoning III', 9]
['Paralyzing Earth', 29]
['Pillage Enchantment', 5]
['Pillar of Fire', 2]
['Pillar of Lightning', 2]
['Plainsight', 1]
['Project Lightning', 3]
['Protection of the Glades', 3]
['Quivering Veil of Xarn', 6]
['Renew Bones', 5]
['Reoccurring Amnesia', 16]
['Resist Magic', 1]
['Retribution of Al`Kabor', 5]
['Scars of Sigil', 1]
['Shiftless Deeds', 6]
['Shroud of Death', 2]
['Spirit of Scale', 3]
['Spirit of the Howler', 1]
['Stun Command', 1]
['Succor', 3]
['Summon Dead', 2]
['Supernova', 2]
['Surge of Enfeeblement', 2]
['Talisman of Jasinth', 3]
['Tears of Prexus', 15]
['Tepid Deeds', 2]
['Thrall of Bones', 1]
['Thunderclap', 4]
['Tigir`s Insects', 12]
['Translocate', 1]
['Trepidation', 1]
['Trucidation', 5]
['Tunare`s Request', 17]
['Vampiric Curse', 3]
['Velocity', 3]
['Vengeance of Al`Kabor', 14]
['Vocarate: Water', 12]
['Wind of Tishanian', 24]
["Wrath of Ap'Sagor", 3]
['Wrath of the Elements', 6]
