['Acumen', 7]
['Aegis', 1]
['Aegis of Ro', 16]
['Aegolism', 15]
['Arch Lich', 19]
['Asphyxiate', 9]
['Avatar', 1]
['Bandoleer of Luclin', 7]
['Banishment', 11]
['Blizzard', 10]
['Boon of the Garou', 2]
['Call of Earth', 1]
['Call of the Predator', 20]
['Cannibalize IV', 2]
['Chill Bones', 3]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 14]
['Death Pact', 3]
['Death Peace', 13]
['Demi Lich', 1]
['Devouring Darkness', 1]
['Divine Strength', 14]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Enforced Reverence', 5]
['Enlightenment', 2]
['Enslave Death', 2]
['Enticement of Flame', 2]
['Entrapping Roots', 13]
['Evacuate', 5]
['Exile Undead', 2]
['Flaming Sword of Xuzl', 15]
['Focus of Spirit', 20]
['Gift of Brilliance', 1]
['Gift of Insight', 2]
['Girdle of Karana', 2]
['Greater Vocaration: Air', 25]
['Greater Vocaration: Fire', 1]
['Greater Vocaration: Water', 3]
['Harmshield', 1]
['Heroic Bond', 12]
['Ice Spear of Solist', 14]
['Improved Invisibility', 1]
['Inferno of Al`Kabor', 4]
['Infusion', 11]
['Invert Gravity', 5]
['Mala', 21]
['Malignant Dead', 1]
['Manasink', 1]
['Manastorm', 23]
['Markar`s Discord', 10]
['Monster Summoning III', 6]
['Pillar of Lightning', 2]
['Protection of the Glades', 1]
['Quivering Veil of Xarn', 11]
['Reckoning', 1]
['Retribution of Al`Kabor', 3]
['Shroud of Death', 1]
['Shroud of Pain', 1]
['Talisman of Jasinth', 2]
['Tears of Prexus', 17]
['Thrall of Bones', 1]
['Tigir`s Insects', 11]
['Trepidation', 1]
['Trucidation', 6]
['Tunare`s Request', 11]
['Velocity', 3]
['Vengeance of Al`Kabor', 13]
['Vocarate: Water', 7]
['Voice of the Berserker', 4]
['Wave of Healing', 1]
['Wind of Tishanian', 23]
['Word of Redemption', 3]
['Wrath of the Elements', 3]
