"""Taken from running python parse_spell_mules.py, this is the output
on the top.
"""

['Abscond', 3]
['Acumen', 10]
['Aegis', 1]
['Aegis of Ro', 22]
['Aegolism', 24]
['Arch Lich', 22]
['Asphyxiate', 22]
['Avatar', 5]
['Bandoleer of Luclin', 14]
['Banishment', 25]
['Banishment of Shadows', 3]
['Blizzard', 16]
['Bonds of Tunare', 2]
['Boon of the Garou', 1]
['Breath of Karana', 7]
['Call of Earth', 2]
['Call of Fire', 1]
['Call of the Predator', 22]
['Cannibalize IV', 2]
['Chill Bones', 3]
['Circle of Cobalt Scar', 1]
['Circle of Great Divide', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 15]
['Conjure Corpse', 2]
['Corporeal Empathy', 2]
['Death Pact', 3]
['Death Peace', 19]
['Defoliation', 1]
['Demi Lich', 3]
['Devouring Darkness', 4]
['Divine Intervention', 2]
['Divine Strength', 25]
['Draught of Jiva', 2]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 5]
['Emissary of Thule', 1]
['Enforced Reverence', 12]
['Enlightenment', 4]
['Enslave Death', 4]
['Enticement of Flame', 4]
['Entrapping Roots', 24]
['Evacuate', 8]
['Exile Undead', 1]
['Fixation of Ro', 1]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 21]
['Focus of Spirit', 20]
['Form of the Great Bear', 1]
['Gift of Brilliance', 6]
['Gift of Insight', 7]
['Girdle of Karana', 7]
['Greater Vocaration: Air', 44]
['Greater Vocaration: Fire', 2]
['Greater Vocaration: Water', 4]
['Harmshield', 2]
['Heroic Bond', 18]
['Ice Spear of Solist', 18]
['Improved Invisibility', 1]
['Inferno of Al`Kabor', 5]
['Infusion', 11]
['Invert Gravity', 7]
['Legacy of Spike', 1]
['Legacy of Thorn', 3]
['Lure of Ice', 3]
['Mala', 38]
['Malignant Dead', 1]
['Malo', 1]
['Manasink', 3]
['Manastorm', 45]
['Markar`s Discord', 11]
['Melody of Ervaj', 1]
['Monster Summoning III', 8]
['Nature Walkers Behest', 2]
['Occlusion of Sound', 5]
['Pillar of Frost', 1]
['Pillar of Lightning', 5]
['Protection of the Glades', 3]
['Quivering Veil of Xarn', 13]
['Rage of Zomm', 3]
['Retribution of Al`Kabor', 3]
['Scars of Sigil', 1]
['Shroud of Death', 4]
['Shroud of Pain', 3]
['Spirit of Oak', 9]
['Stun Command', 2]
['Succor', 1]
['Talisman of the Raptor', 1]
['Tears of Druzzil', 3]
['Tears of Prexus', 18]
['The Unspoken Word', 1]
['Theft of Thought', 1]
['Thunderbold', 2]
['Tigir`s Insects', 11]
['Translocate', 2]
['Trucidation', 7]
['Tunare`s Request', 12]
['Velocity', 4]
['Vengeance of Al`Kabor', 13]
['Visions of Grandeur', 1]
['Vocarate: Fire', 1]
['Vocarate: Water', 8]
['Voice of the Berserker', 7]
['Wake of Tranquility', 3]
['Wave of Healing', 5]
['Wind of Tishanian', 30]
['Winds of Gelid', 1]
['Word of Redemption', 9]
['Word of Restoration', 1]
['Word of Souls', 1]
['Wrath of the Elements', 4]
['Yaulp IV', 3]
