['Acumen', 10]
['Aegis', 1]
['Aegis of Ro', 16]
['Aegolism', 16]
['Allure', 14]
['Arch Lich', 24]
['Asphyxiate', 6]
['Augment', 1]
['Bandoleer of Luclin', 8]
['Banishment', 8]
['Berserker Strength', 1]
['Blanket of Forgetfulness', 7]
['Blast of Poison', 1]
['Blaze', 1]
['Blizzard', 11]
['Boltran`s Animation', 1]
['Bond of Death', 13]
['Bonds of Tunare', 1]
['Boon of the Garou', 2]
['Breath of Karana', 7]
['Cackling Bones', 7]
['Call of Bones', 1]
['Call of Earth', 1]
['Call of the Predator', 23]
['Cannibalize IV', 3]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 5]
['Circle of Wakening Lands', 2]
['Cobalt Scar Portal', 1]
['Color Skew', 12]
['Column of Fire', 1]
['Column of Lightning', 1]
['Composition of Ervaj', 17]
['Cornucopia', 1]
['Corporeal Empathy', 5]
['Death Peace', 23]
['Divine Strength', 16]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Enforced Reverence', 1]
['Enlightenment', 11]
['Enslave Death', 1]
['Enticement of Flame', 8]
['Entrapping Roots', 7]
['Evacuate', 1]
['Everfount', 3]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Eye of Tallon', 2]
['Feedback', 6]
['Flame Arc', 2]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 10]
['Focus of Spirit', 20]
["Force Spiral of Al'Kabor", 1]
['Form of the Hunter', 3]
['Gift of Insight', 1]
['Gravity Flux', 5]
['Greater Conjuration: Air', 5]
['Greater Conjuration: Fire', 3]
['Greater Conjuration: Water', 11]
['Greater Summoning: Earth', 2]
['Greater Vocaration: Air', 24]
['Greater Vocaration: Fire', 1]
['Harmshield', 5]
['Haunting Corpse', 1]
['Heroic Bond', 15]
['Ice Spear of Solist', 17]
['Improved Invisibility', 1]
['Infusion', 12]
['Insipid Weakness', 12]
['Intensify Death', 2]
['Invisibility to Undead', 1]
['Invoke Death', 3]
['Invoke Shadow', 1]
['Lich', 10]
['Mala', 22]
['Malignant Dead', 2]
['Mana Sieve', 15]
['Manastorm', 24]
['Markar`s Discord', 15]
['Mesmerization', 1]
['Mind Wipe', 5]
['Modulating Rod', 1]
['Monster Summoning III', 8]
['Nature Walkers Behest', 1]
['Paralyzing Earth', 30]
['Pillage Enchantment', 5]
['Pillar of Fire', 3]
['Pillar of Lightning', 2]
['Project Lightning', 5]
['Protection of the Glades', 6]
['Quivering Veil of Xarn', 6]
['Radiant Visage', 1]
['Regrowth of the Grove', 2]
['Renew Bones', 6]
['Reoccurring Amnesia', 19]
['Resist Magic', 1]
['Retribution of Al`Kabor', 5]
['Scars of Sigil', 1]
['Shiftless Deeds', 7]
['Shroud of Death', 2]
['Spirit of Oak', 1]
['Spirit of Scale', 1]
['Succor', 4]
['Summon Dead', 2]
['Summon Shard of the Core', 1]
['Supernova', 2]
['Talisman of Jasinth', 3]
['Tears of Prexus', 15]
['Tepid Deeds', 2]
['Thrall of Bones', 1]
['Thunderclap', 4]
['Tigir`s Insects', 12]
['Translocate', 1]
['Trepidation', 1]
['Trucidation', 6]
['Tunare`s Request', 17]
['Vampiric Curse', 3]
['Velocity', 3]
['Vengeance of Al`Kabor', 14]
['Vocarate: Water', 12]
['Wave of Healing', 1]
['Wind of Tishanian', 26]
["Wrath of Ap'Sagor", 3]
['Wrath of the Elements', 6]
['Zumaik`s Animation', 1]
