"""Taken from running python parse_spell_mules.py, this is the output
on the top.
"""

['Acumen', 9]
['Aegis of Ro', 23]
['Aegolism', 22]
['Arch Lich', 22]
['Asphyxiate', 22]
['Avatar', 4]
['Bandoleer of Luclin', 14]
['Banishment', 23]
['Banishment of Shadows', 2]
['Blizzard', 16]
['Boon of the Garou', 1]
['Breath of Karana', 6]
['Call of Earth', 2]
['Call of Fire', 1]
['Call of the Predator', 20]
['Cannibalize IV', 1]
['Chill Bones', 3]
['Circle of Cobalt Scar', 1]
['Circle of Great Divide', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 14]
['Conjure Corpse', 2]
['Corporeal Empathy', 1]
['Death Pact', 3]
['Death Peace', 15]
['Demi Lich', 3]
['Devouring Darkness', 4]
['Divine Strength', 22]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 5]
['Emissary of Thule', 1]
['Enforced Reverence', 10]
['Enlightenment', 4]
['Enslave Death', 4]
['Enticement of Flame', 3]
['Entrapping Roots', 23]
['Evacuate', 6]
['Fixation of Ro', 1]
['Flaming Sword of Xuzl', 19]
['Focus of Spirit', 20]
['Gift of Brilliance', 6]
['Gift of Insight', 6]
['Girdle of Karana', 6]
['Greater Vocaration: Air', 45]
['Greater Vocaration: Fire', 2]
['Greater Vocaration: Water', 4]
['Harmshield', 2]
['Heroic Bond', 16]
['Ice Spear of Solist', 16]
['Improved Invisibility', 2]
['Inferno of Al`Kabor', 4]
['Infusion', 11]
['Invert Gravity', 6]
['Legacy of Spike', 1]
['Legacy of Thorn', 2]
['Mala', 38]
['Malignant Dead', 1]
['Malo', 1]
['Manasink', 2]
['Manastorm', 46]
['Markar`s Discord', 10]
['Monster Summoning III', 8]
['Nature Walkers Behest', 2]
['Occlusion of Sound', 3]
['Pillar of Frost', 1]
['Pillar of Lightning', 3]
['Plainsight', 1]
['Protection of the Glades', 3]
['Quivering Veil of Xarn', 13]
['Rage of Zomm', 3]
['Retribution of Al`Kabor', 2]
['Scars of Sigil', 1]
['Shroud of Death', 4]
['Shroud of Pain', 3]
['Spirit of Oak', 9]
['Stun Command', 1]
['Tears of Druzzil', 2]
['Tears of Prexus', 17]
['Thunderbold', 1]
['Tigir`s Insects', 11]
['Torpor', 1]
['Trucidation', 7]
['Tunare`s Request', 12]
['Velocity', 4]
['Vengeance of Al`Kabor', 12]
['Visions of Grandeur', 2]
['Vocarate: Fire', 1]
['Vocarate: Water', 8]
['Voice of the Berserker', 5]
['Wake of Tranquility', 2]
['Wave of Healing', 1]
['Wind of Tishanian', 30]
['Word of Redemption', 8]
['Word of Souls', 1]
['Wrath of the Elements', 4]
