['Acumen', 8]
['Aegis of Ro', 17]
['Aegolism', 17]
['Allure', 6]
['Arch Lich', 19]
['Asphyxiate', 5]
['Avatar', 1]
['Bandoleer of Luclin', 8]
['Banishment', 3]
['Berserker Strength', 1]
['Blanket of Forgetfulness', 2]
['Blast of Poison', 1]
['Blaze', 1]
['Blizzard', 10]
['Boltran`s Animation', 1]
['Bond of Death', 5]
['Breath of Karana', 3]
['Cackling Bones', 4]
['Call of Bones', 6]
['Call of the Hero', 1]
['Call of the Predator', 22]
['Cannibalize III', 1]
['Cannibalize IV', 3]
['Cast Force', 1]
['Chilling Embrace', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 1]
['Circle of Wakening Lands', 2]
['Color Shift', 1]
['Color Skew', 7]
['Color Slant', 1]
['Column of Fire', 1]
['Column of Lightning', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Conjure Corpse', 1]
['Corporeal Empathy', 4]
['Dead Man Floating', 6]
['Death Peace', 19]
['Divine Strength', 15]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Energy Storm', 1]
['Enlightenment', 9]
['Enslave Death', 1]
['Enticement of Flame', 6]
['Entrapping Roots', 1]
['Everfount', 2]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Feedback', 4]
["Fire Spiral of Al'Kabor", 4]
['Fist of Karana', 1]
['Flame Arc', 2]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 9]
['Focus of Spirit', 19]
["Force Spiral of Al'Kabor", 1]
['Gift of Brilliance', 2]
['Gift of Insight', 3]
['Gravity Flux', 4]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 1]
['Greater Conjuration: Water', 6]
['Greater Summoning: Earth', 2]
['Greater Vocaration: Air', 27]
['Greater Vocaration: Fire', 2]
['Greater Vocaration: Water', 1]
['Harmshield', 2]
['Haunting Corpse', 5]
['Heroic Bond', 12]
['Hungry Earth', 8]
['Ice Spear of Solist', 18]
['Improved Invisibility', 1]
['Infusion', 10]
['Insipid Weakness', 11]
['Intensify Death', 4]
['Invert Gravity', 1]
['Invoke Death', 3]
['Invoke Shadow', 3]
['Lava Storm', 8]
['Lich', 6]
['Lightning Storm', 4]
['Lure of Ice', 1]
['Mala', 24]
['Malignant Dead', 3]
['Mana Sieve', 10]
['Manastorm', 23]
['Markar`s Discord', 11]
['Mesmerization', 2]
['Mind Wipe', 3]
['Monster Summoning III', 12]
['Paralyzing Earth', 25]
['Pillar of Fire', 7]
['Pillar of Lightning', 2]
['Project Lightning', 1]
['Protection of the Glades', 1]
['Quiver of Marr', 2]
['Quivering Veil of Xarn', 1]
['Renew Bones', 5]
['Reoccurring Amnesia', 15]
['Restless Bones', 1]
['Retribution of Al`Kabor', 3]
['Scars of Sigil', 1]
['Shiftless Deeds', 2]
["Shock Spiral of Al'Kabor", 4]
['Shroud of Death', 1]
['Spirit of the Howler', 2]
['Stun Command', 1]
['Succor', 1]
['Summon Dead', 2]
['Talisman of Jasinth', 1]
['Tears of Prexus', 13]
['Thrall of Bones', 1]
['Thunderclap', 11]
['Tigir`s Insects', 15]
['Trepidation', 1]
['Trucidation', 2]
['Tunare`s Request', 14]
['Upheaval', 2]
['Vampiric Curse', 6]
['Velocity', 2]
['Vengeance of Al`Kabor', 12]
['Vocarate: Water', 12]
['Voice of the Berserker', 1]
['Wind of Tishanian', 25]
["Wrath of Ap'Sagor", 8]
['Wrath of the Elements', 6]
