"""Taken from running python parse_spell_mules.py, this is the output
on the top.
"""

['Acumen', 9]
['Aegis', 2]
['Aegis of Ro', 25]
['Aegolism', 21]
['Arch Lich', 22]
['Asphyxiate', 22]
['Avatar', 4]
['Bandoleer of Luclin', 14]
['Banishment', 23]
['Banishment of Shadows', 1]
['Blizzard', 16]
['Boon of the Garou', 1]
['Breath of Karana', 7]
['Call of Earth', 2]
['Call of Fire', 1]
['Call of the Predator', 20]
['Cannibalize IV', 2]
['Chill Bones', 4]
['Circle of Cobalt Scar', 1]
['Circle of Great Divide', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 14]
['Conjure Corpse', 2]
['Corporeal Empathy', 1]
['Death Pact', 2]
['Death Peace', 15]
['Demi Lich', 3]
['Devouring Darkness', 3]
['Divine Strength', 22]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 5]
['Enforced Reverence', 10]
['Enlightenment', 3]
['Enslave Death', 4]
['Enticement of Flame', 3]
['Entrapping Roots', 23]
['Evacuate', 5]
['Exile Undead', 1]
['Fixation of Ro', 1]
['Flame of Light', 1]
['Flaming Sword of Xuzl', 18]
['Focus of Spirit', 20]
['Frost', 1]
['Gift of Brilliance', 6]
['Gift of Insight', 5]
['Girdle of Karana', 7]
['Greater Vocaration: Air', 46]
['Greater Vocaration: Fire', 2]
['Greater Vocaration: Water', 4]
['Harmshield', 2]
['Heroic Bond', 15]
['Ice Spear of Solist', 16]
['Improved Invisibility', 2]
['Inferno of Al`Kabor', 4]
['Infusion', 11]
['Invert Gravity', 5]
['Legacy of Spike', 1]
['Legacy of Thorn', 2]
['Mala', 39]
['Malignant Dead', 1]
['Malo', 1]
['Manasink', 1]
['Manastorm', 48]
['Markar`s Discord', 10]
['Monster Summoning III', 8]
["Naltron's Mark", 1]
['Nature Walkers Behest', 2]
['Occlusion of Sound', 1]
['Pillar of Frost', 1]
['Pillar of Lightning', 2]
['Plainsight', 1]
['Protection of the Glades', 4]
['Quivering Veil of Xarn', 13]
['Rage of Zomm', 2]
['Retribution of Al`Kabor', 2]
['Scars of Sigil', 1]
['Shroud of Death', 4]
['Shroud of Pain', 3]
['Spirit of Oak', 9]
['Stun Command', 1]
['Tears of Druzzil', 2]
['Tears of Prexus', 17]
['Tigir`s Insects', 11]
['Torpor', 1]
['Trucidation', 8]
['Tunare`s Request', 13]
['Velocity', 5]
['Vengeance of Al`Kabor', 12]
['Vocarate: Fire', 1]
['Vocarate: Water', 8]
['Voice of the Berserker', 5]
['Wave of Healing', 1]
['Wind of Tishanian', 29]
['Word of Redemption', 8]
['Wrath of the Elements', 4]
