"""
Taken from running python parse_spell_mules.py --count
"""

['Acumen', 8]
['Aegis', 2]
['Aegis of Ro', 16]
['Aegolism', 18]
['Arch Lich', 20]
['Asphyxiate', 10]
['Avatar', 3]
['Bandoleer of Luclin', 7]
['Banishment', 14]
['Blizzard', 14]
['Boon of the Garou', 2]
['Breath of Karana', 4]
['Call of Earth', 1]
['Call of Fire', 2]
['Call of the Predator', 20]
['Cannibalize IV', 2]
['Chill Bones', 4]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 14]
['Corporeal Empathy', 1]
['Death Pact', 3]
['Death Peace', 14]
['Demi Lich', 2]
['Devouring Darkness', 2]
['Divine Strength', 14]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Enforced Reverence', 7]
['Enlightenment', 2]
['Enslave Death', 3]
['Enticement of Flame', 2]
['Entrapping Roots', 16]
['Evacuate', 5]
['Exile Undead', 3]
['Flaming Sword of Xuzl', 15]
['Focus of Spirit', 21]
['Gift of Brilliance', 3]
['Gift of Insight', 4]
['Girdle of Karana', 4]
['Greater Vocaration: Air', 25]
['Greater Vocaration: Fire', 1]
['Greater Vocaration: Water', 3]
['Harmshield', 1]
['Heroic Bond', 14]
['Ice Spear of Solist', 15]
['Improved Invisibility', 1]
['Inferno of Al`Kabor', 4]
['Infusion', 11]
['Invert Gravity', 5]
['Mala', 21]
['Malignant Dead', 1]
['Manasink', 1]
['Manastorm', 23]
['Markar`s Discord', 10]
['Monster Summoning III', 6]
["Naltron's Mark", 1]
['Nature Walkers Behest', 1]
['Occlusion of Sound', 1]
['Pillar of Lightning', 2]
['Protection of the Glades', 3]
['Quivering Veil of Xarn', 12]
['Reckoning', 1]
['Retribution of Al`Kabor', 3]
['Shroud of Death', 2]
['Shroud of Pain', 2]
['Spirit of Oak', 1]
['Talisman of Jasinth', 2]
['Talisman of the Serpent', 1]
['Tears of Prexus', 17]
['Thrall of Bones', 1]
['Tigir`s Insects', 11]
['Trepidation', 1]
['Trucidation', 7]
['Tunare`s Request', 12]
['Velocity', 3]
['Vengeance of Al`Kabor', 13]
['Visions of Grandeur', 1]
['Vocarate: Water', 7]
['Voice of the Berserker', 4]
['Wave of Healing', 1]
['Wind of Tishanian', 23]
['Word of Redemption', 4]
['Wrath of the Elements', 3]
