['Acumen', 9]
['Aegis of Ro', 16]
['Aegolism', 14]
['Arch Lich', 20]
['Asphyxiate', 9]
['Atol`s Spectral Shackles', 1]
['Avatar', 1]
['Bandoleer of Luclin', 7]
['Banishment', 7]
['Blast of Poison', 2]
['Blizzard', 10]
['Boon of the Garou', 4]
['Breath of Karana', 6]
['Call of Earth', 1]
['Call of the Predator', 20]
['Cannibalize IV', 1]
['Chill Bones', 5]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Wakening Lands', 2]
['Composition of Ervaj', 15]
['Conjure Corpse', 2]
['Corporeal Empathy', 3]
['Death Pact', 2]
['Death Peace', 15]
['Demi Lich', 1]
['Devouring Darkness', 1]
['Divine Strength', 15]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Energy Storm', 2]
['Enforced Reverence', 3]
['Enlightenment', 9]
['Enslave Death', 2]
['Enticement of Flame', 3]
['Entrapping Roots', 11]
['Evacuate', 3]
['Exile Undead', 2]
['Fixation of Ro', 1]
['Flame of Light', 1]
['Flaming Sword of Xuzl', 14]
['Focus of Spirit', 19]
['Frost', 1]
['Gift of Insight', 2]
['Gift of Pure Thought', 1]
['Girdle of Karana', 3]
['Greater Vocaration: Air', 24]
['Greater Vocaration: Fire', 1]
['Greater Vocaration: Water', 1]
['Harmshield', 1]
['Heroic Bond', 13]
['Ice Spear of Solist', 16]
['Improved Invisibility', 2]
['Inferno of Al`Kabor', 4]
['Infusion', 12]
['Invert Gravity', 5]
['Levant', 1]
['Mala', 19]
['Malignant Dead', 1]
['Manasink', 2]
['Manastorm', 23]
['Markar`s Discord', 12]
['Monster Summoning III', 4]
["Naltron's Mark", 1]
['Pillar of Lightning', 2]
['Protection of the Glades', 3]
['Quivering Veil of Xarn', 12]
['Reckoning', 5]
['Retribution of Al`Kabor', 4]
['Summon: Muzzle of Mardu', 1]
['Talisman of Jasinth', 3]
['Tears of Prexus', 18]
['Thrall of Bones', 1]
['Tigir`s Insects', 12]
['Trepidation', 1]
['Trucidation', 7]
['Tunare`s Request', 12]
['Velocity', 2]
['Vengeance of Al`Kabor', 13]
['Vocarate: Water', 9]
['Voice of the Berserker', 3]
['Wave of Healing', 1]
['Wind of Tishanian', 26]
['Word of Redemption', 1]
['Wrath of the Elements', 3]
