['Acumen', 9]
['Aegis of Ro', 17]
['Aegolism', 19]
['Allure', 8]
['Arch Lich', 21]
['Asphyxiate', 5]
['Augmentation of Death', 1]
['Avatar', 2]
['Bandoleer of Luclin', 8]
['Banishment', 6]
['Banshee Aura', 1]
['Berserker Strength', 1]
['Blanket of Forgetfulness', 4]
['Blast of Poison', 1]
['Blaze', 1]
['Blizzard', 12]
['Boltran`s Animation', 1]
['Bond of Death', 7]
['Breath of Karana', 5]
['Cackling Bones', 5]
['Call of the Hero', 1]
['Call of the Predator', 21]
['Cannibalize IV', 2]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 5]
['Circle of Wakening Lands', 2]
['Cobalt Scar Portal', 1]
['Color Skew', 10]
['Column of Fire', 1]
['Column of Lightning', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Earth', 1]
['Conjuration: Fire', 1]
['Conjuration: Water', 1]
['Conjure Corpse', 1]
['Cornucopia', 1]
['Corporeal Empathy', 4]
['Dead Man Floating', 8]
['Death Peace', 20]
['Divine Strength', 15]
['Draught of Jiva', 2]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 3]
['Energy Storm', 2]
['Enforced Reverence', 1]
['Enlightenment', 11]
['Enticement of Flame', 7]
['Entrapping Roots', 5]
['Evacuate', 2]
['Everfount', 3]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Eye of Tallon', 1]
['Feedback', 5]
["Fire Spiral of Al'Kabor", 5]
['Fixation of Ro', 1]
['Flame Arc', 2]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 11]
['Focus of Spirit', 18]
["Force Spiral of Al'Kabor", 1]
['Frost', 1]
['Gift of Brilliance', 4]
['Gift of Insight', 5]
['Gravity Flux', 5]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 4]
['Greater Conjuration: Fire', 4]
['Greater Conjuration: Water', 9]
['Greater Summoning: Earth', 2]
['Greater Vocaration: Air', 25]
['Greater Vocaration: Fire', 2]
['Harmshield', 3]
['Heroic Bond', 15]
['Hungry Earth', 1]
['Ice Spear of Solist', 19]
['Improved Invisibility', 2]
['Infusion', 11]
['Insipid Weakness', 11]
['Invert Gravity', 1]
['Invoke Death', 2]
['Lich', 5]
['Lightning Storm', 5]
['Mala', 22]
['Mana Sieve', 14]
['Manasink', 1]
['Manastorm', 23]
['Markar`s Discord', 13]
['Mesmerization', 1]
['Mind Wipe', 4]
['Monster Summoning III', 12]
['Nature Walkers Behest', 1]
['Paralyzing Earth', 37]
['Pillage Enchantment', 3]
['Pillar of Fire', 10]
['Pillar of Lightning', 2]
['Project Lightning', 2]
['Protection of the Glades', 3]
['Quivering Veil of Xarn', 3]
['Renew Bones', 2]
['Reoccurring Amnesia', 15]
['Resist Magic', 1]
['Restless Bones', 1]
['Retribution of Al`Kabor', 5]
['Scars of Sigil', 1]
['Shiftless Deeds', 5]
["Shock Spiral of Al'Kabor", 5]
['Shroud of Death', 1]
['Spirit of Scale', 1]
['Spirit of the Howler', 1]
['Stun Command', 1]
['Succor', 2]
['Summon Dead', 2]
['Supernova', 3]
['Surge of Enfeeblement', 1]
['Talisman of Jasinth', 2]
['Talisman of the Cat', 1]
['Tears of Prexus', 15]
['Thunderclap', 2]
['Tigir`s Insects', 16]
['Torment of Argli', 1]
['Trepidation', 1]
['Trucidation', 4]
['Tunare`s Request', 16]
['Upheaval', 1]
['Vampiric Curse', 2]
['Velocity', 2]
['Vengeance of Al`Kabor', 14]
['Vocarate: Water', 12]
['Wind of Tishanian', 26]
['Winds of Gelid', 1]
["Wrath of Ap'Sagor", 9]
['Wrath of the Elements', 6]
