['Acumen', 7]
['Aegis of Ro', 17]
['Aegolism', 18]
['Allure', 3]
['Arch Lich', 19]
['Asphyxiate', 4]
['Avatar', 2]
['Bandoleer of Luclin', 8]
['Banishment', 3]
['Banishment of Shadows', 1]
['Berserker Strength', 1]
['Blaze', 1]
['Blizzard', 9]
['Bond of Death', 3]
['Boon of the Clear Mind', 1]
['Breath of Karana', 3]
['Cackling Bones', 4]
['Call of Bones', 3]
['Call of the Hero', 1]
['Call of the Predator', 20]
['Cannibalize III', 2]
['Cannibalize IV', 3]
['Cast Force', 1]
['Chilling Embrace', 1]
['Chords of Dissonance', 4]
['Circle of Cobalt Scar', 1]
['Circle of Force', 1]
['Circle of Wakening Lands', 2]
['Circle of Winter', 1]
['Color Shift', 1]
['Color Skew', 6]
['Color Slant', 1]
['Column of Fire', 1]
['Column of Lightning', 1]
['Composition of Ervaj', 15]
['Conjuration: Air', 1]
['Conjuration: Fire', 1]
['Convergence', 2]
['Corporeal Empathy', 4]
['Dead Man Floating', 5]
['Death Pact', 1]
['Death Peace', 19]
['Defoliation', 2]
['Demi Lich', 1]
['Divine Strength', 15]
['Draught of Jiva', 1]
['Dyzil`s Deafening Decoy', 2]
['Elemental Maelstrom', 4]
['Endure Magic', 1]
['Energy Storm', 1]
['Enlightenment', 9]
['Enslave Death', 1]
['Enticement of Flame', 7]
['Entrapping Roots', 1]
['Evacuate', 3]
['Everfount', 2]
['Exile Undead', 1]
['Extinguish Fatigue', 1]
['Feedback', 4]
["Fire Spiral of Al'Kabor", 4]
['Fist of Karana', 1]
['Flame Arc', 2]
['Flame of Light', 3]
['Flaming Sword of Xuzl', 9]
['Focus of Spirit', 19]
["Force Spiral of Al'Kabor", 1]
['Forlorn Deeds', 1]
['Gift of Brilliance', 1]
['Gift of Insight', 2]
['Gravity Flux', 4]
['Great Divide Portal', 1]
['Greater Conjuration: Air', 1]
['Greater Conjuration: Water', 5]
['Greater Summoning: Earth', 1]
['Greater Vocaration: Air', 28]
['Greater Vocaration: Fire', 2]
['Harmshield', 2]
['Haunting Corpse', 5]
['Heroic Bond', 13]
['Hungry Earth', 8]
['Ice Spear of Solist', 17]
['Improved Invisibility', 2]
['Inferno of Al`Kabor', 2]
['Infusion', 10]
['Insipid Weakness', 10]
['Intensify Death', 4]
['Invert Gravity', 3]
['Invoke Death', 1]
['Invoke Shadow', 1]
['Lava Storm', 8]
['Lich', 4]
['Lightning Storm', 4]
['Mala', 25]
['Malignant Dead', 3]
['Mana Sieve', 8]
['Manastorm', 23]
['Mark of Karn', 1]
['Markar`s Discord', 10]
['Mesmerization', 2]
['Mind Wipe', 1]
['Monster Summoning III', 12]
['Paralyzing Earth', 24]
['Pillar of Fire', 7]
['Pillar of Frost', 2]
['Pillar of Lightning', 2]
['Project Lightning', 1]
['Protection of the Glades', 1]
['Quiver of Marr', 2]
['Quivering Veil of Xarn', 1]
['Radiant Visage', 1]
['Reckoning', 1]
['Regrowth of the Grove', 1]
['Renew Bones', 5]
['Reoccurring Amnesia', 13]
['Restless Bones', 1]
['Retribution of Al`Kabor', 4]
['Scale of Wolf', 1]
['Scars of Sigil', 1]
["Shock Spiral of Al'Kabor", 4]
['Shroud of Death', 2]
['Spirit of the Howler', 3]
['Stun Command', 1]
['Succor', 1]
['Summon Dead', 2]
['Summon: Muzzle of Mardu', 1]
['Talisman of Jasinth', 3]
['Tears of Prexus', 14]
['Thrall of Bones', 1]
['Thunderclap', 11]
['Tigir`s Insects', 15]
['Trucidation', 2]
['Tunare`s Request', 14]
['Upheaval', 2]
['Vampiric Curse', 6]
['Velocity', 2]
['Vengeance of Al`Kabor', 12]
['Vocarate: Water', 12]
['Voice of the Berserker', 1]
['Wake of Tranquility', 2]
['Wind of Tishanian', 24]
['Word of Redemption', 1]
["Wrath of Ap'Sagor", 8]
['Wrath of the Elements', 5]
